### ISSUE TITLE
html/template Inheritance: Buffer Pool Changes

### ISSUE THREAD

**Issue by jcbwlkr** [elithrar/elithrar.github.io#1]
Thanks for this post. It helped me quite a bit.

In the section regarding rendering to a `bytes.Buffer` the example code says

```go
buf := bufpool.Get()
err := tmpl.ExecuteTemplate(&buf, "base", data)
```

When I copy this directly I get the error
    
    cannot use &buf (type **bytes.Buffer) as type io.Writer in argument to tmpl.ExecuteTemplate:**bytes.Buffer does not implement io.Writer (missing Write method)

`buf` is already a `*bytes.Buffer` so we don't need to take it's address. Simple enough to fix but someone might get caught up on it.

Also maybe the example should `defer bufpool.Put(buf)` instead of closing it in two places. Again, this would make it more likely that developers copying/pasting sections will actually return the buffer to the pool.

Thanks again :+1:

**Comment by elithrar** [comment]
Great catch and thanks for pointing it out. I've fixed this now, although I recall the reason why I *didn't* use defer (slight performance hit). I'll use defer in this example though to keep it simple for readers as failing to return the buffer to the pool will result in a not-immediate bug that can bite users.

Thanks again!
