### ISSUE TITLE
Tiny issues in latest article

### ISSUE THREAD

**Issue by ottob** [elithrar/elithrar.github.io#3]
Thanks for all of your very educational posts.

I think there are two very minor issues in the latests article (testing-http-handlers-go)

In the first code example for TestGetProjectsHandler change ` goji.HandlerFunc(GetUsersHandler)` to `handler := goji.HandlerFunc(GetUsersHandler)` and in the second code sample for TestGetProjectsHandlerError change ` Handler{env, GetProjectsHandler)` to `handler := Handler{env, GetProjectsHandler)`?

**Comment by elithrar** [comment]
Thanks for pointing this out @ottob - typos on my part!

**Comment by elithrar** [comment]
Fixed in 1674dd3449722841f0008acc0a2063c44b702cc0
