### ISSUE TITLE
Incorrect links in Feed

### ISSUE THREAD

**Issue by ankitrgadiya** [elithrar/elithrar.github.io#7]
The article links in Atom feed is incorrect.

```xml
<link href="http://blog.questionable.services///blog.questionable.services/article/building-go-projects-on-circle-ci/"/>
```

This is because [the template](https://github.com/elithrar/elithrar.github.io/blob/master/atom.xml#L22) uses `{{ site.url}}{{ site.baseurl }}...` template. To fix it, the `baseurl` variable in [`_config.yaml`](https://github.com/elithrar/elithrar.github.io/blob/master/_config.yml#L16) can be set to `/`.

https://blog.questionable.services/atom.xml

**Comment by elithrar** [comment]
This should be fixed as of 2aa76bd15cd7dc35c927f83851598fd5a87ca868
